## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'oceanseabreeze'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_template become pymodaq_plugins_daqmx for instance)

package-url = 'none' #to modify
description = 'A plugin for controlling the small Oceanoptics spectrometers using the seabreeze module'

author = 'Nicolas Tappy'
author-email = 'nicolas.tappy@epfl.ch'
license = 'All your codez are belong to us.'

[plugin-install]
#packages required for your plugin:
packages-required = ['seabreeze']